yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [path('author/', views.AboutAuthorView.as_view(), name='author'),
               path('tech/', views.AboutTechView.as_view(), name='tech'),
               ]

yatube/posts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [path('', views.index, name='index'),
               path('profile/<str:username>/',
                    views.profile,
                    name='profile'
                    ),
               path('posts/<int:post_id>/',
                    views.post_detail,
                    name='post_detail'
                    ),
               path('group/<slug:slug>/',
                    views.group_posts,
                    name='group_list'
                    ),
               path('create/', views.post_create, name='post_create'),
               path('posts/<int:post_id>/edit/',
                    views.post_edit,
                    name='post_edit'
                    ),
               path('posts/<int:post_id>/comment/',
                    views.add_comment,
                    name='add_comment'
                    ),
               path('follow/', views.follow_index, name='follow_index'),
               path('profile/<str:username>/follow/',
                    views.profile_follow,
                    name='profile_follow'
                    ),
               path('profile/<str:username>/unfollow/',
                    views.profile_unfollow,
                    name='profile_unfollow'
                    ),
               ]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               )
    group = models.ForeignKey(Group,
                              on_delete=models.SET_NULL,
                              blank=True,
                              null=True
                              )
    image = models.ImageField('Картинка',
                              upload_to='posts/',
                              blank=True
                              )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date', 'author']
        default_related_name = 'posts'
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             blank=True,
                             null=True,
                             related_name='comments'
                             )
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='comments'
                               )
    text = text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created', 'author', 'post']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='follower'
                             )
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='following'
                               )

    class Meta:
        ordering = ['user']
        verbose_name = 'Подписку'
        verbose_name_plural = 'Подписки'

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page
from utils import paginator

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User


@cache_page(20, key_prefix="index_page")
def index(request):
    template = 'posts/index.html'
    posts = Post.objects.select_related('author', 'group').all()
    page_obj = paginator.page(posts, request)
    context = {'page_obj': page_obj, }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('group').all()
    page_obj = paginator.page(posts, request)
    context = {'group': group,
               'page_obj': page_obj,
               }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    user = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author_id=user.id)
    post_count = posts.count()
    page_obj = paginator.page(posts, request)
    following = user.following.exists()
    context = {'page_obj': page_obj,
               'author': user,
               'post_count': post_count,
               'following': following,
               }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    comments = Comment.objects.filter(post_id=post_id)
    form = CommentForm(request.POST or None)
    post_count = Post.objects.filter(author_id=post.author.id).count()
    context = {'post_count': post_count,
               'post': post,
               'form': form,
               'comments': comments,
               }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        new_post.save()
        return redirect('posts:profile', new_post.author)
    context = {'form': form, }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if post.author != request.user:
        return redirect('posts:index')
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post.id)
    return render(request, template, {'form': form, 'is_edit': True, })


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator.page(posts, request)
    context = {'page_obj': page_obj, }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if user != author:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.get(user=request.user, author=author).delete()
    return redirect('posts:follow_index')

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
{% endif %}
{% endblock title %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">       
            {% if is_edit %}
              Редактировать запись
            {% else %}
              Добавить запись
            {% endif %}               
          </button>              
        </div>
        <div class="card-body">  
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}
          <form method="post" enctype="multipart/form-data" action="">
            {% csrf_token %}            
            <div class="form-group row my-3 p-3">
              <label for="id_text">
                Текст поста                  
                <span class="required text-danger" >*</span>                  
              </label>
              {{ form.text }}                 
              <small id="id_text-help" class="form-text text-muted">
                Текст нового поста
              </small>                  
            </div>            
            <div class="form-group row my-3 p-3">
              <label for="id_group">
                Группа                  
              </label>
              {{ form.group }}
                <small id="id_group-help" class="form-text text-muted">
                  Группа, к которой будет относиться пост
                </small>
            </div>
            {% if is_edit %}
            <div class="form-group row my-3 p-3">
              <label for="id_image">
              Изображение                 
              </label>
              {{ form.image }}
                <small id="id_group-help" class="form-text text-muted">
                </small>
            </div>
            {% else %}
            <div class="form-group row my-3 p-3">
              <label for="id_image">
                Добавьте изображение                      
              </label>
              <input type="file" name="image" accept="image/*" class="form-control" id="id_image">                      
            </div>
            {% endif %}
              <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}               
              </button> 
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Мои подписки{% endblock %}
{% block content %}
  <h1>Мои подписки</h1>
  {% include 'includes/posts.html' %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}
{% block content %}
  <h1>Записи сообщества: {{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}   
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
        <a href="{% url 'posts:profile' post.author %}">
          Все посты пользователя
        </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
    </article>
    <p>{{ post.text }}</p>
    <p>{% if post.group %}   
      <a href="{% url 'posts:post_detail' post.id %}">Подробная информация </a>
      <br>
      <a href="{% url 'posts:group_list' post.group.slug %}">
        Все записи группы: {{ post.group }}
      </a>
      {% endif %}
      </p>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
  {% include 'includes/paginator.html' %} 
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  <h1>Последние обновления на сайте</h1>
  {% include 'includes/switcher.html' %}
  {% include 'includes/posts.html' %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock title %}

{% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}
              <li class="list-group-item">
                Группа: "{{ post.group }}" - 
                <a href="{% url 'posts:group_list' post.group.slug %}">
                  все записи группы
                </a>
              </li>
            {% endif %} 
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post_count }}</span>
            </li>
            <li class="list-group-item">
              <a href={% url 'posts:profile' post.author %}>
                все посты пользователя
              </a>
            </li>
            <li class="list-group-item">
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
          {% if post.author == request.user  %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            Редактировать запись
          </a>  
          {% endif %} 
          {% include 'includes/comments.html' %}
        </article>
      </div> 
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Профайл пользователя {{ author }}
{% endblock title %}
{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя {{ author }}</h1>
    <h3>Всего постов: {{ post_count }}</h3>
    {% include 'includes/subscribe.html' %}
  </div>
  {% include 'includes/posts.html' %}      
  {% include 'includes/paginator.html' %} 
{% endblock content %}